backend:
  name: github
  repo: chaucodes/portfolio
  branch: main

media_folder: static/content/blog
public_folder: /public

collections:
  - name: blog
    label: Blog
    folder: static/content/blog
    slug: 'index'
    create: true
    fields:
      - { name: slug, label: Slug }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
